### ISSUE TITLE
Variable explanation

### ISSUE THREAD

**Issue by AverageDaniel** [BradyPlanden/LiiBRA.jl#43]
Hello, first of all nice work :) Currently I am looking into some simulations are a bit unsure of what all the outputs given from the function "Simulate" are. Does someone know if it is available on the github page and I have missed? If not it could be nice to include :)

Best regards

**Comment by DarioSlaifsteinSk** [comment]
Hi, Daniel
You can check the publication [here](https://linkinghub.elsevier.com/retrieve/pii/S2352152X22016255).
The variable definitions are stored in the names of the Tuple `Results`
```julia
Results, tₑ = Simulate(Cell, Input, Def, Tk, SList, SOC, A₀, B₀, C₀, D₀, t)
```
```julia
julia> keys(Results)
(:θₙ, :θₚ, :jeqₙ, :jeqₚ, :x, :y, :Cseₙ, :Cseₚ, :Ce, :η₀, :ηₙ, :ηL, :ηₚ, :ϕ_ẽ1, :ϕ_ẽ2, :ϕse₀ⁿ, :jₙ, :j₀, :jₚ, 
:jL, :Rₜⁿ, :Rₜᵖ, :Uocpⁿ, :Uocpᵖ, :Cell_V, :ϕ_e, :Cell_SOC, :Iapp, :t, :tₑ)
```

**Comment by AverageDaniel** [comment]
Thank you :)

**Comment by BradyPlanden** [comment]
Closing this issue and opening #46.
